# Integration test for the following packages:
# https://github.com/scikit-hep/awkward/blob/main/.github/workflows/test.yml
# https://github.com/dask-contrib/dask-awkward/blob/main/.github/workflows/pypi-tests.yml
# https://github.com/scikit-hep/uproot5/blob/main/.github/workflows/build-test.yml
# https://github.com/scikit-hep/vector/blob/main/.github/workflows/ci.yml
# https://github.com/scikit-hep/boost-histogram/blob/develop/.github/workflows/weekly.yml
# https://github.com/scikit-hep/hist/blob/main/.github/workflows/ci.yml
# https://github.com/dask-contrib/dask-histogram/blob/main/.github/workflows/ci.yml
# https://github.com/scikit-hep/coffea/blob/master/.github/workflows/ci.yml

name: Integration Tests

on:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 2 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.13", "3.14"]
        dask-client: ["with", "without"]

    name: Test (${{ matrix.os }}) - ðŸ ${{ matrix.python-version }}, ${{ matrix.dask-client }} dask

    env:
      FILENAME: results-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.dask-client }}.md

    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Sync env
        run: |
          git lfs install --skip-smudge
          uv sync

      - name: Clone scikit-hep/awkward
        uses: actions/checkout@v4
        with:
          repository: scikit-hep/awkward
          path: repo-awkward
          submodules: true
          ref: "main"
          fetch-depth: 0

      - name: Clone dask-contrib/dask-awkward
        uses: actions/checkout@v4
        with:
          repository: dask-contrib/dask-awkward
          path: repo-dask-awkward
          ref: "main"
          fetch-depth: 0
          lfs: true

      - name: Clone scikit-hep/uproot5
        uses: actions/checkout@v4
        with:
          repository: scikit-hep/uproot5
          path: repo-uproot5
          ref: "main"
          fetch-depth: 0

      - name: Clone scikit-hep/vector
        uses: actions/checkout@v4
        with:
          repository: scikit-hep/vector
          path: repo-vector
          ref: "main"
          fetch-depth: 0

      - name: Clone scikit-hep/boost-histogram
        uses: actions/checkout@v4
        with:
          repository: scikit-hep/boost-histogram
          path: repo-boost-histogram
          submodules: true
          ref: "develop"
          fetch-depth: 0

      - name: Clone scikit-hep/hist
        uses: actions/checkout@v4
        with:
          repository: scikit-hep/hist
          path: repo-hist
          ref: "main"
          fetch-depth: 0

      - name: Clone dask-contrib/dask-histogram
        uses: actions/checkout@v4
        with:
          repository: dask-contrib/dask-histogram
          path: repo-dask-histogram
          ref: "main"
          fetch-depth: 0

      - name: Clone scikit-hep/coffea
        uses: actions/checkout@v4
        with:
          repository: scikit-hep/coffea
          path: repo-coffea
          ref: "master"
          fetch-depth: 0

      - name: Build awkward-cpp and awkward
        run: |
          cd repo-awkward
          uvx nox -s prepare -- --headers --signatures --tests
          uv pip install -vv . ./awkward-cpp -r requirements-test-full.txt -r requirements-test-ml.txt

      - name: Build dask-awkward
        run: |
          cd repo-dask-awkward
          uv pip install '.[complete,test]'

      - name: Build uproot
        run: |
          cd repo-uproot5
          uv pip install . --group=dev

      - name: Build vector
        run: |
          cd repo-vector
          uv pip install . --group=dev --group=test-all-gil

      - name: Build boost-histogram
        run: |
          cd repo-boost-histogram
          uv pip install -v . --group=test

      - name: Build hist
        run: |
          cd repo-hist
          uv pip install -e . --group=test --group=dask

      - name: Build dask-histogram
        run: |
          cd repo-dask-histogram
          uv pip install -e '.[test]'

      - name: Build coffea
        run: |
          cd repo-coffea
          uv pip install '.[dev,dask]'

      - name: Add xdist
        run: uv pip uninstall pytest-benchmark
        run: uv pip install pytest-xdist


      - name: Show all versions
        run: uv pip list

      - name: Test scikit-hep/awkward
        id: test-awkward
        run: |
          cd repo-awkward
          if uv run --project .. pytest -vv -rs tests ${{ matrix.os != 'windows-latest' && '-n 4' || '' }} --timeout=1000; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test dask-contrib/dask-awkward
        id: test-dask-awkward
        run: |
          cd repo-dask-awkward
          if uv run --project .. pytest -vv -rs tests --reruns 10 --reruns-delay 30 --timeout=1000; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test scikit-hep/uproot5
        id: test-uproot
        run: |
          cd repo-uproot5
          if uv run --project .. pytest -vv -rs tests --reruns 10 --reruns-delay 30 --only-rerun "(?i)http|ssl|timeout|expired|connection|socket" --timeout=1000; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test scikit-hep/vector
        id: test-vector
        run: |
          cd repo-vector
          if uv run --project .. pytest -vv -rs tests --ignore tests/test_notebooks.py -n 4 --timeout=1000; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test scikit-hep/boost-histogram
        id: test-boost-histogram
        run: |
          cd repo-boost-histogram
          if uv run --project .. pytest -vv -rs tests --timeout=1000; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test scikit-hep/hist
        id: test-hist
        run: |
          cd repo-hist
          if uv run --project .. pytest -vv -rs tests --timeout=1000; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test dask-contrib/dask-histogram
        id: test-dask-histogram
        run: |
          cd repo-dask-histogram
          if uv run --project .. pytest -vv -rs tests --timeout=1000; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Test scikit-hep/coffea (${{ matrix.dask-client }} dask Client)
        id: test-coffea
        run: |
          cd repo-coffea
          if uv run --project .. pytest -vv -rs tests --deselect=test_taskvine -m "${{ matrix.dask-client == 'without' && 'not ' || '' }}dask_client" ${{ matrix.dask-client == 'without' && '-n 4' || '' }} --timeout=1000; then
            echo "success=true" >> $GITHUB_OUTPUT
          else
            echo "success=false" >> $GITHUB_OUTPUT
          fi

      - name: Save results to file
        run: |
          echo -n "| ${{ matrix.os }}, Python${{ matrix.python-version }}, ${{ matrix.dask-client }} Dask | " > $FILENAME
          echo -n "${{ steps.test-awkward.outputs.success == 'true' && 'âœ…' || 'âŒ' }} | " >> $FILENAME
          echo -n "${{ steps.test-dask-awkward.outputs.success == 'true' && 'âœ…' || 'âŒ' }} | " >> $FILENAME
          echo -n "${{ steps.test-uproot.outputs.success == 'true' && 'âœ…' || 'âŒ' }} | " >> $FILENAME
          echo -n "${{ steps.test-vector.outputs.success == 'true' && 'âœ…' || 'âŒ' }} | " >> $FILENAME
          echo -n "${{ steps.test-boost-histogram.outputs.success == 'true' && 'âœ…' || 'âŒ' }} | " >> $FILENAME
          echo -n "${{ steps.test-hist.outputs.success == 'true' && 'âœ…' || 'âŒ' }} | " >> $FILENAME
          echo -n "${{ steps.test-dask-histogram.outputs.success == 'true' && 'âœ…' || 'âŒ' }} | " >> $FILENAME
          echo "${{ steps.test-coffea.outputs.success == 'true' && 'âœ…' || 'âŒ' }} | " >> $FILENAME

      - name: Upload results artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILENAME }}
          path: ${{ env.FILENAME }}

      - name: Check if tests failed
        run: |
          echo ${{ steps.test-awkward.outputs.success == 'true' && ' ' || 'Awkward tests failed' }}
          echo ${{ steps.test-dask-awkward.outputs.success == 'true' && ' ' || 'Dask-Awkward tests failed' }}
          echo ${{ steps.test-uproot.outputs.success == 'true' && ' ' || 'Uproot tests failed' }}
          echo ${{ steps.test-vector.outputs.success == 'true' && ' ' || 'Vector tests failed' }}
          echo ${{ steps.test-boost-histogram.outputs.success == 'true' && ' ' || 'Boost-Histogram tests failed' }}
          echo ${{ steps.test-hist.outputs.success == 'true' && ' ' || 'Hist tests failed' }}
          echo ${{ steps.test-dask-histogram.outputs.success == 'true' && ' ' || 'Dask-Histogram tests failed' }}
          echo ${{ steps.test-coffea.outputs.success == 'true' && ' ' || 'Coffea tests failed' }}
          # Fail the job if any of the tests failed
          # Ignore the output outcome of dask-awkward since it's flaky
          ${{ (steps.test-awkward.outputs.success == 'true' && steps.test-uproot.outputs.success == 'true' && steps.test-vector.outputs.success == 'true' && steps.test-boost-histogram.outputs.success == 'true' && steps.test-hist.outputs.success == 'true' && steps.test-dask-histogram.outputs.success == 'true' && steps.test-coffea.outputs.success == 'true') && 'true' || 'false' }}


  summary:
    name: Collect results
    runs-on: ubuntu-latest
    needs: test
    if: always()

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
          path: results

      - name: Generate final summary
        run: |
          echo "---" > final_results.md
          echo "| System Configuration | Awkward | Dask-Awkward | Uproot | Vector | Boost-Histogram | Hist | Dask-Histogram | Coffea |" >> final_results.md
          echo "| --- | --- | --- | --- | --- | --- | --- | --- | --- |" >> final_results.md
          cat results/*.md >> final_results.md
          cat final_results.md > $GITHUB_STEP_SUMMARY
